# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['app\\wr_voice.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('app\\Webrapid-logo-W.png', 'app'),
        ('app\\logo.png', 'app'),
        ('assets\\logo.ico', 'assets'),
        ('config.json', '.'),
    ],
    hiddenimports=[
        'faster_whisper',
        'ctranslate2',
        'huggingface_hub',
        'sounddevice',
        'soundfile',
        'numpy',
        'pyperclip',
        'keyboard',
        'PIL',
        'pystray',
        'plyer.platforms.win.notification',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'torchaudio',
        'transformers',
        'tensorflow', 'keras',
        'matplotlib', 'scipy', 'pandas',
        'IPython', 'jupyter', 'notebook',
        'pytest', 'unittest',
        'setuptools', 'pip', 'wheel',
        'tkinter.test', 'lib2to3',
    ],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WR Voice BETA',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets\\logo.ico'],
)
